### ISSUE TITLE
how to create iotrule1 and iotrule2

### ISSUE THREAD

**Issue by shreya199609** [aws-samples/aws-appsync-iot-core-realtime-example#1]

**Comment by dave-moser** [comment]
The rules should be created by the Amplify project when you execute an 'amplify push' command.  Do you see them in your AWS Account in IoT Core?

**Comment by shreya199609** [comment]
no i can't see them

**Comment by dave-moser** [comment]
OK, are you receiving any errors when you execute the amplify push command?  Perhaps you can copy the output of that command and provide it here.

**Comment by bcalegaro** [comment]
Hello there,
i have the same question, and maybe is not here the place to ask but,
i got everything working, then i want to make my own project to exercice.

How to create a iot rule with amplify? I can create graphql api and lambad, but what about the iot rule? I know that i can enter de console and do manually but i want a javascript code.

Care to enlighten me?

**Comment by dave-moser** [comment]
Here are the instructions to add custom Cloud Formation stacks to your Amplify project:

https://docs.amplify.aws/cli/usage/customcf

You create the proper folder structure under your amplify/backend folder then modify the amplify/backend/backend-config.json file to pull your templates into the overall build.
