### ISSUE TITLE
appsync lambda connection

### ISSUE THREAD

**Issue by sidd2217** [aws-samples/aws-appsync-iot-core-realtime-example#11]
Hi ,
 I'm new to aws, so if I'm wrong somewhere please guide me.
 I went through this link [https://aws.amazon.com/blogs/mobile/iot-with-aws-appsync/]() and came here.
It's not explained in detail on how do i actually connect aws-lambda to appsync.
The code given doesn't work when i try to copy paste it in lambda function.

So can anyone guide me through this?

Working - AWS-iot core messages arriving at lambda.
Pending - Send the messages to appsync.

Here's my lambda code

`    exports.lambda_handler = async (event) => 
{
    const response = {
        statusCode: 200,
        body: JSON.stringify(event),
    };
    return response;
};
`

OS- Win10
IOT - ESP32
App - React-native

**Comment by NourNafea** [comment]
hey, did you solve this problem?

**Comment by sidd2217** [comment]
> hey, did you solve this problem?

Nope, Still searching for it.

**Comment by dave-moser** [comment]
Hi.  The code in this sample for a Lambda function that sends data to AppSync can be found in this file:

https://github.com/aws-samples/aws-appsync-iot-core-realtime-example/blob/master/mobile/amplify/backend/function/createsensorvalue/src/index.js
