### ISSUE TITLE
DynamoDB table not updated anymore

### ISSUE THREAD

**Issue by farmsensor** [aws-samples/aws-appsync-iot-core-realtime-example#5]
Since todays update the DynamoDB table is not updated anymore.

**Comment by farmsensor** [comment]
Before the update it worked fine getting updates from the sensor script.

**Comment by farmsensor** [comment]
I reinstalled the environment again and now it works perfect!

**Comment by dave-moser** [comment]
Sorry - I did some major refactoring.  I wanted to illustrate an AppSync Lambda Resolver to retrieve the sensor information. The sensor metadata is now stored on the IoT Shadow of the Sensor.  There is a Lambda function - getSensor - that retrieves the sensor name and type.  The DynamoDB table only stores the sensor readings over time.  Thanks for trying it out!
