### ISSUE TITLE
[request] Could you extend the readme with steps to recreate the AWS Services config?

### ISSUE THREAD

**Issue by agreeff** [aws-samples/aws-appsync-iot-core-realtime-example#9]
>First off: please excuse the potentially noob-ish request, but I am very much in the "learning AWS" stage at the moment.. I would very much like to make sure I don't miss things. I found this repo while reading through the "[Monitoring IoT devices in real time with AWS AppSync](https://aws.amazon.com/blogs/mobile/iot-with-aws-appsync/)" blog post, but looking through and even running this in my AWS profile has left me with more questions than answers.

I'm currently trying to recreate this same system with freshly generated projects (already created a more verbose Inquirer.js powered CLI tool for mocking Things), but now I'm a little stuck with creating a new app for viewing both real-time and historic data.

Suffice to say, it's not all that easy for us AWS newbies to extrapolate which options we should and shouldn't pick when adding services (i.e. with `amplify <category> add`) in a fresh project, with the intension of reproducing the "same" system in our own stacks.

For example, with adding services using Amplify, `amplify --help` tells me that `<category> is one of: notifications, analytics, api, auth, function, hosting, interactions, predictions, storage, xr`. How does that help with adding an IoT rule though? Researching AWS services for my current side project, this repo and it's associated guide have been one of the most useful resources for me, but it still feels like I'm missing *something*, just not sure what it is.

---

As for my actual request here: could I ask that somebody please update this repo's root readme file with a bit more info, specifically with regards to generating the relevant AWS Services used in the `mobile` project?

**Comment by dave-moser** [comment]
Hi.  Thanks for the questions.  As you mentioned, the Amplify CLI natively supports certain services (api, auth, function, etc...).  It can also be extended to create and manage any other services, such as the IoT Rule I use in my sample.  Here is a good dock on how this is done:

https://docs.amplify.aws/cli/usage/customcf/

If you follow that and compare it to the amplify resources in my project, you will see how I added the IoT Rule.
